"""removed is_confirmed and added planning_response in the booking table

Revision ID: 243731485988
Revises: 9674d395c068
Create Date: 2026-01-06 09:19:46.898553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '243731485988'
down_revision: Union[str, Sequence[str], None] = '9674d395c068'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('planning_response', sa.JSON(), nullable=True))
    op.drop_column('booking', 'is_confirmed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('is_confirmed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('booking', 'planning_response')
    # ### end Alembic commands ###
