"""removed planning_response  and added title in the booking table

Revision ID: 54f0dc33bc64
Revises: 243731485988
Create Date: 2026-01-24 10:27:49.790967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '54f0dc33bc64'
down_revision: Union[str, Sequence[str], None] = '243731485988'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('title', sa.String(), nullable=False))
    op.drop_column('booking', 'planning_response')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('planning_response', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('booking', 'title')
    # ### end Alembic commands ###
